services:
  - type: web
    name: kotlinithub-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: JDBC_DATABASE_URL
        sync: false
      - key: JDBC_DATABASE_USERNAME
        sync: false
      - key: JDBC_DATABASE_PASSWORD
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: "6379"
      - key: RABBITMQ_HOST
        sync: false
      - key: RABBITMQ_PORT
        value: "5672"
      - key: RABBITMQ_USERNAME
        sync: false
      - key: RABBITMQ_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: BOOTSTRAP_ADMIN_EMAIL
        value: admin@gmail.com
      - key: BOOTSTRAP_ADMIN_PASSWORD
        sync: false
      - key: BOOTSTRAP_ADMIN_NAME
        value: Render Admin
