db.url=jdbc:postgresql://localhost:5432/toy_store
db.user=postgres
db.password=postgres
images.directory=resources/images/products
images.placeholder=resources/images/picture.png
images.icon=resources/images/icon.png
